stages:
  - test
  - build
  - deploy

.build_template: &build_template
  rules:
    - changes:
        - app/**/*
        - components/**/*
        - lib/**/*
        - shared/**/*
        - db/**/*
        - scripts/**/*
        - locales/**/*
        - server/**/*
        - patches/**/*
        - Dockerfile
        - .dockerignore
        - package.json
        - pnpm-lock.yaml
        - pnpm-workspace.yaml
        - react-router.config.ts
        - vite.config.ts
        - tsconfig.json
        - postcss.config.mjs
        - proxy.ts
        - .gitlab-ci.yml

build:
  stage: build
  image: reg.mikumikumi.xyz/base/kaniko-builder:latest
  <<: *build_template
  needs: [test]
  script:
    - export BUILD_DOCKERFILE=Dockerfile.ci
    - export BUILD_DESTINATION="reg.mikumikumi.xyz/kaoru/dashboard:${CI_COMMIT_SHORT_SHA}"
    - build

test:
  stage: test
  image: reg.mikumikumi.xyz/mirror/node:20
  <<: *build_template
  before_script:
    - npm install -g pnpm@10
    - pnpm install --frozen-lockfile
  script:
    - pnpm run lint
    - pnpm run typecheck

deploy:
  stage: deploy
  image: reg.mikumikumi.xyz/base/kubectl:latest
  needs: [build]
  <<: *build_template
  script:
    - echo "${KUBECONFIG}" > ~/.kube/config
    - "kubectl set image -n kaoru statefulset/dashboard dashboard=reg.mikumikumi.xyz/kaoru/dashboard:${CI_COMMIT_SHORT_SHA} --kubeconfig ~/.kube/config"
