
import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("login", "login/page.tsx"),
  layout("(dashboard)/layout.tsx", [
    index("(dashboard)/page.tsx"),
    route("overview", "(dashboard)/overview/page.tsx"),
    route("accounts", "(dashboard)/accounts/page.tsx"),
    route("x", "(dashboard)/x/page.tsx"),
    route("x/:id", "(dashboard)/x/[id]/page.tsx"),
    route("github", "(dashboard)/github/page.tsx"),
    route("github/:accountId", "(dashboard)/github/[accountId]/page.tsx"),
    route("github/:accountId/repos/:repoId", "(dashboard)/github/[accountId]/repos/[repoId]/page.tsx"),
    route("gitlab", "(dashboard)/gitlab/page.tsx"),
    route("gitlab/:accountId", "(dashboard)/gitlab/[accountId]/page.tsx"),
    route("gitlab/:accountId/projects/:projectId", "(dashboard)/gitlab/[accountId]/projects/[projectId]/page.tsx"),
    route("reddit", "(dashboard)/reddit/page.tsx"),
    route("reddit/:id", "(dashboard)/reddit/[id]/page.tsx"),
    route("analytics", "(dashboard)/analytics/page.tsx"),
    route("revenue", "(dashboard)/revenue/page.tsx"),
    route("app-store", "(dashboard)/app-store/page.tsx"),
    route("ai", "(dashboard)/ai/page.tsx"),
    route("settings", "(dashboard)/settings/page.tsx"),
    route("admin", "(dashboard)/admin/page.tsx"),
  ]),

  route("a/e", "a/e/route.ts"),
  route("api/accounts/:id", "api/accounts/[id]/route.ts"),
  route("api/accounts", "api/accounts/route.ts"),
  route("api/app-store/connections/:id/analytics/sync", "api/app-store/connections/[id]/analytics/sync/route.ts"),
  route("api/app-store/connections/:id/revenue/sync", "api/app-store/connections/[id]/revenue/sync/route.ts"),
  route("api/app-store/connections/:id/backfill", "api/app-store/connections/[id]/backfill/route.ts"),
  route("api/app-store/connections", "api/app-store/connections/route.ts"),
  route("api/app-store/connections/:id", "api/app-store/connections/[id]/route.ts"),
  route("api/app-store/connections/:id/refresh", "api/app-store/connections/[id]/refresh/route.ts"),
  route("api/app-store/connections/:id/analytics", "api/app-store/connections/[id]/analytics/route.ts"),
  route("api/app-store/connections/:id/apps/:appId", "api/app-store/connections/[id]/apps/[appId]/route.ts"),
  route("api/auth/change-password", "api/auth/change-password/route.ts"),
  route("api/auth/login", "api/auth/login/route.ts"),
  route("api/auth/logout", "api/auth/logout/route.ts"),
  route("api/auth/me", "api/auth/me/route.ts"),
  route("api/graphql", "api/graphql/route.ts"),
  route("api/analytics/sites", "api/analytics/sites/route.ts"),
  route("api/analytics/sites/:id", "api/analytics/sites/[id]/route.ts"),
  route("api/bing-wallpaper", "api/bing-wallpaper/route.ts"),
  route("api/confirm/token", "api/confirm/token/route.ts"),
  route("api/fetch/:id", "api/fetch/[id]/route.ts"),
  route("api/ai/chat", "api/ai/chat/route.ts"),
  route("api/settings", "api/settings/route.ts"),
  route("api/github/repos/pin", "api/github/repos/pin/route.ts"),
  route("api/github/watchlist/:accountId", "api/github/watchlist/[accountId]/route.ts"),
  route("api/gitlab/projects/pin", "api/gitlab/projects/pin/route.ts"),
  route("api/health", "api/health/route.ts"),
  route("api/reddit/callback", "api/reddit/callback/route.ts"),
  route("api/users/:id", "api/users/[id]/route.ts"),
  route("api/users", "api/users/route.ts"),
  route("api/*", "catch-all/api-route.ts"),
  route("*", "catch-all/route.tsx"),

] satisfies RouteConfig;
