
import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("login", "login/page.tsx"),
  layout("(dashboard)/layout.tsx", [
    index("(dashboard)/page.tsx"),
    route("overview", "(dashboard)/overview/page.tsx"),
    route("accounts", "(dashboard)/accounts/page.tsx"),
    route("x", "(dashboard)/x/page.tsx"),
    route("x/:id", "(dashboard)/x/[id]/page.tsx"),
    route("github", "(dashboard)/github/page.tsx"),
    route("github/:accountId", "(dashboard)/github/[accountId]/page.tsx"),
    route("github/:accountId/repos/:repoId", "(dashboard)/github/[accountId]/repos/[repoId]/page.tsx"),
    route("gitlab", "(dashboard)/gitlab/page.tsx"),
    route("gitlab/:accountId", "(dashboard)/gitlab/[accountId]/page.tsx"),
    route("gitlab/:accountId/projects/:projectId", "(dashboard)/gitlab/[accountId]/projects/[projectId]/page.tsx"),
    route("reddit", "(dashboard)/reddit/page.tsx"),
    route("reddit/:id", "(dashboard)/reddit/[id]/page.tsx"),
    route("ai", "(dashboard)/ai/page.tsx"),
    route("settings", "(dashboard)/settings/page.tsx"),
    route("admin", "(dashboard)/admin/page.tsx"),
  ]),

route("api/accounts/:id", "api/accounts/[id]/route.ts"),
  route("api/accounts", "api/accounts/route.ts"),
  route("api/auth/change-password", "api/auth/change-password/route.ts"),
  route("api/auth/login", "api/auth/login/route.ts"),
  route("api/auth/logout", "api/auth/logout/route.ts"),
  route("api/auth/me", "api/auth/me/route.ts"),
  route("api/bing-wallpaper", "api/bing-wallpaper/route.ts"),
  route("api/confirm/token", "api/confirm/token/route.ts"),
  route("api/fetch/:id", "api/fetch/[id]/route.ts"),
  route("api/fetch-health", "api/fetch-health/route.ts"),
  route("api/pulse", "api/pulse/route.ts"),
  route("api/top-content", "api/top-content/route.ts"),
  route("api/ai/chat", "api/ai/chat/route.ts"),
  route("api/settings", "api/settings/route.ts"),
  route("api/github/:accountId/repos/:repoId/clones", "api/github/[accountId]/repos/[repoId]/clones/route.ts"),
  route("api/github/:accountId/repos/:repoId/paths/history", "api/github/[accountId]/repos/[repoId]/paths/history/route.ts"),
  route("api/github/:accountId/repos/:repoId/paths", "api/github/[accountId]/repos/[repoId]/paths/route.ts"),
  route("api/github/:accountId/repos/:repoId/referrers/history", "api/github/[accountId]/repos/[repoId]/referrers/history/route.ts"),
  route("api/github/:accountId/repos/:repoId/referrers", "api/github/[accountId]/repos/[repoId]/referrers/route.ts"),
  route("api/github/:accountId/repos/:repoId/releases/:releaseId/assets", "api/github/[accountId]/repos/[repoId]/releases/[releaseId]/assets/route.ts"),
  route("api/github/:accountId/repos/:repoId/releases/growth", "api/github/[accountId]/repos/[repoId]/releases/growth/route.ts"),
  route("api/github/:accountId/repos/:repoId/releases", "api/github/[accountId]/repos/[repoId]/releases/route.ts"),
  route("api/github/:accountId/repos/:repoId", "api/github/[accountId]/repos/[repoId]/route.ts"),
  route("api/github/:accountId/repos/:repoId/snapshots", "api/github/[accountId]/repos/[repoId]/snapshots/route.ts"),
  route("api/github/:accountId/repos/:repoId/views", "api/github/[accountId]/repos/[repoId]/views/route.ts"),
  route("api/github/contributions/:accountId", "api/github/contributions/[accountId]/route.ts"),
  route("api/github/overview/:accountId", "api/github/overview/[accountId]/route.ts"),
  route("api/github/repos/pin", "api/github/repos/pin/route.ts"),
  route("api/github/sources/:accountId/available", "api/github/sources/[accountId]/available/route.ts"),
  route("api/github/timeline/:accountId", "api/github/timeline/[accountId]/route.ts"),
  route("api/github/watchlist/:accountId", "api/github/watchlist/[accountId]/route.ts"),
  route("api/gitlab/:accountId/projects/:projectId/releases", "api/gitlab/[accountId]/projects/[projectId]/releases/route.ts"),
  route("api/gitlab/:accountId/projects/:projectId", "api/gitlab/[accountId]/projects/[projectId]/route.ts"),
  route("api/gitlab/:accountId/projects/:projectId/snapshots", "api/gitlab/[accountId]/projects/[projectId]/snapshots/route.ts"),
  route("api/gitlab/contributions/:accountId", "api/gitlab/contributions/[accountId]/route.ts"),
  route("api/gitlab/overview/:accountId", "api/gitlab/overview/[accountId]/route.ts"),
  route("api/gitlab/projects/pin", "api/gitlab/projects/pin/route.ts"),
  route("api/gitlab/timeline/:accountId", "api/gitlab/timeline/[accountId]/route.ts"),
  route("api/health", "api/health/route.ts"),
  route("api/reddit/activity/:accountId", "api/reddit/activity/[accountId]/route.ts"),
  route("api/reddit/callback", "api/reddit/callback/route.ts"),
  route("api/reddit/comments/:accountId", "api/reddit/comments/[accountId]/route.ts"),
  route("api/reddit/overview/:accountId", "api/reddit/overview/[accountId]/route.ts"),
  route("api/reddit/posts/:accountId", "api/reddit/posts/[accountId]/route.ts"),
  route("api/reddit/subreddits/:accountId", "api/reddit/subreddits/[accountId]/route.ts"),
  route("api/reddit/timeline/:accountId", "api/reddit/timeline/[accountId]/route.ts"),
  route("api/stats/calendar", "api/stats/calendar/route.ts"),
  route("api/stats/overview", "api/stats/overview/route.ts"),
  route("api/stats/timeline", "api/stats/timeline/route.ts"),
  route("api/stats/top", "api/stats/top/route.ts"),
  route("api/tweets/:id", "api/tweets/[id]/route.ts"),
  route("api/tweets", "api/tweets/route.ts"),
  route("api/users/:id", "api/users/[id]/route.ts"),
  route("api/users", "api/users/route.ts"),
  route("api/*", "catch-all/api-route.ts"),
  route("*", "catch-all/route.tsx"),

] satisfies RouteConfig;
